version: '2'

# Docker and Docker Compose based environment for Drupal.

services:
# Web node
  web:
    hostname: web
    image: fjmk/docker-drupal:prod
    environment:
      - DOCROOT=docroot                         # change to your drupal root (html, build)
    volumes:
      # Project root folder mapping
      - &project_root ".:/var/www"
    links:
      - db
    depends_on:
      - "db"
      
  # DB node
  db:
    hostname: db
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=drupal
