version: '2'

# Docker and Docker Compose based environment for Drupal.

services:
# Web node
  resolvable:
    hostname: resolvable
    image: mgood/resolvable
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "/etc/resolv.conf:/tmp/resolv.conf"
    networks:
      - app_net
      
  web:
    hostname: web
    image: fjmk/docker-drupal7:prod
    environment:
      - DOCROOT=docroot                         # change to your drupal root (html, build)
    volumes:
      # Project root folder mapping
      - &project_root ".:/var/www"
    links:
      - db
    networks:
      - app_net
    depends_on:
      - "resolvable"
      - "db"
      
  # DB node
  db:
    hostname: db
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=drupal
    networks:
      - app_net
    depends_on:
      - "resolvable"
  
  # selenium2 node
  # Uncomment the service definition section below and the link in the web service above to start using selenium2 driver for Behat tests requiring JS support.
  browser:
    hostname: browser
    image: selenium/standalone-chrome
    ports:
      - "4444"
    environment:
      - DOMAIN_NAME=selenium.browser
    networks:
      - app_net
    depends_on:
      - "resolvable"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1
