#!/bin/bash

set -e

chmod 1777 /tmp

# initialize files when first run
if [ ! -f /opt/done ]; then
  
  # set the docroot depending on your drupal development application, ex: /var/www, var/www/docroot
  sed -i "s@DocumentRoot /var/www/html@DocumentRoot /var/www/$DOCROOT@" /etc/apache2/sites-available/000-default.conf
  sed -i "s@DocumentRoot /var/www/html@DocumentRoot /var/www/$DOCROOT@" /etc/apache2/apache2.conf

  a2ensite 000-default
  ln -sf /dev/stdout /var/log/apache2/access.log && ln -sf /dev/stderr /var/log/apache2/error.log

  # don't check remote ssh hosts
  mkdir -p /root/.ssh; chmod 700 /root/.ssh
  cat << EOF > /root/.ssh/config
Host *
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel QUIET
EOF

# set /opt/done
touch /opt/done
fi
