#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down container"
    /etc/init.d/ssh stop
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting sshd"

/etc/init.d/ssh start

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

## not needed? while pgrep -u root sshd > /dev/null; do sleep 1; done
