#!/bin/bash

set -e

chmod 1777 /tmp

# initialize files when first run
if [ ! -f /opt/done ]; then
  
  # set the docroot depending on your drupal development application, ex: /var/www, var/www/docroot
  sed -i "s@DocumentRoot /var/www/html@DocumentRoot /var/www/$DOCROOT@" /etc/apache2/sites-available/000-default.conf
  sed -i "s@DocumentRoot /var/www/html@DocumentRoot /var/www/$DOCROOT@" /etc/apache2/apache2.conf

  a2ensite 000-default
  ln -sf /dev/stdout /var/log/apache2/access.log && ln -sf /dev/stderr /var/log/apache2/error.log

# set /opt/done
touch /opt/done
fi
